---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: newrelic-secret
  namespace: newrelic
spec:
  encryptedData:
    licenseKey: AgAhPvZJvbrjRepjuXSQS/ALv6noSF+b/Fyhjfb8eLK3GW6hQrUkjpx4BGxjLdgORddkAQMYN2AnIf5m/iJMIBcuqX3gAqU9j1bgPYXN/Nd/sP6WQB5CzTnJhpyoMH1zskdIzxLndkAj3Xhe3G5E6jRvbhWQxh41QqcJktFqmUKI0a0bjj2n0R1mt8+0Tx/1aJr+3eiN1tRJ9KGxVW/Qy8s2jDpfTEESOf5uFxsrZHbPhCqlNCLM3OVT/NjGrmOidy8IWQFa3Ot3EOKyKu19BYn4XyVCcPsOue25klZnxa1V+TisH2boH4iFYn6OV1aZtjQgkPAIebPThxCFcnBGwMHALvhY34RtsQF1O1a4Q2CIwn2sleTQEgMFrqisTM85VDxQpd+49qNDK5LSEbwC/jCmcfMqinz8QWpOpcvCxEZSr2DQmen17YPaD9TTJ5LpccukG6FNSUSHIYLqbrfRk5ZKPCtq56Toa+qC0zT7OPCywePK+Y1Pt4taKxgIMPwy36pxY/QfTfVwLAZHJ1KH3dSn90IpXei6/4LzV79CGSv1g0HeD4k4MYt/UQcxDinA6c9DEYT/nTotgdFH6hWy0HmysXlMGNJ6is4GlNWyOCKq6A01C9RJJcUjdbUbi4psX76f+OLOENXxf06sNORW8WT+5YXk8iIvglY52v9uOSvxeF8bIVGmqpESOyFieJZP9wBmLO5oMr4LSmaGr3bvLNIzxYLwgBGxPzzRDrf0u7NTemdjdFsTC393
  template:
    metadata:
      name: newrelic-secret
      namespace: newrelic
