---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mqttui-app
  namespace: iot-tools
spec:
  encryptedData:
    admin-password: AgAC3XCmVpIwshSajnQJM1WGu471rfM4z89kyZLLxIUtot6Rj0m8JYqfnZMxXQf8G+wihybeksZ31cxOttsSFnhJOHpq4d8ooIYUZoqVRpYKzE9Om48flvJDfwmcyFlTjht5MPaKVNDKlT491dXbPPLWRKweB4TxzeLYjsTQkt8gkt6IhrFK/vhNib1FDhycGoe5iHEyDCL6z/sR4oyHpbrEtfMsy/N7ZYiANab7xSRhdFeWuoruGOsUqcvKGes8lZZ8DhD4GyVqtGHTnokGiS67ue3kxcWF4W0cOk5KzBCNmchz1N6I15zzFrbNMwxrIMXGbObViN6U5XbRPBfz5IOqSjfkQfpEB3jJGkrgoJ8Y8GPVwiNlRaMvFmKsY8VeMceA7BBkt6f/RrE9O/FmmtnM/Idtr4fnBN1U4H3Twnx0EwL+/DcCk0D2TfABqxvIFYNLPbOTObpduccJr7r1kVzrsaWV3ZRSKbdEQnm+OlVkWgrFdCU8UVsZBhSrrk4PK+U1JTAoDikcBgwyPXpJCEVs8D8vNuNiCzfo0fzhnvWsC4rvYGaxd/DP589bWeys8UFJIywy/ajJuw8mdeW5jFIVRGivSLUbp4gEB2ITcD4e/H9fj+wBT/6Gj3kMIU7dXWqpM4tQV/h3PxvqifLl5YvZEijUcwKX8aLbFiw0zyvb+ISlbKXouZX6EnLG/tWmQeHfAfAaUbgLcf4SwSNvyLCgWSN/0pYU8ns=
    secret-key: AgAuTNMW3yQ0go8e9dXsTnAX/7Ma+Dl8B5IaH+zrA9sjC31kfbhMt5wgUUzP8nXxnK5YF7XKbvLpe7PcozhDsWe1p7VAijlj2aSk4MLe7u4LsgqhxJSoo2I3kLzFfzIqFwiZuYnECuTwd/PwPl/jd55nkUykKhcRSgFeFXeCjHUEFsv6GtIQr+H2JO+0Pnm/iMeCgQLxIuXsY1teQLQnBmi/oaU11qJs85qkYs3dVxsOuObUytuzVmgbMOiGduDyor8/eEzjSUtfhHYWi93u7LTxQNPWvl+QmsiDeHT0vLyZUwOCNzkqMsZTmLnTAeyTaAQrTJMT5oQc3R6YsVPUSG7/r7vbHIKU2YEgwoL8EReMjHpLbMfaRy3nM1gMfzamA/if7mGZT/00gWHqRLbyb4lzYcwjQ/V0mIKM5t7YX2NJDjCVeKsXk6WzXv4BRahuFx6spq03GsGanselk4qm7DCNO5N8h8BPLfmBkKKk8lwKwy6wjt/KhXFqpez+o5vbFi9kYGSxbttKDkLdYkvMZTjRNLspmi24Pl4/Obtz3anDOycaiswC+uBCtSIxGlv6mBcwhM3/Aa7I8jMQKBMQfIMlL21CSSgFZDoLF6+GZt8a0eoW13iEdy7JiZcedT18YBoAO2UeZBxo/Ioh9I6v8iX+QdWDY7rYmbh0RgJSI/z8iwOs8icym70PLKXpdV+JOA0ia3FyGetwjat4sop0AvCgEtNjkF38L/sauWpBAJccxgzXTuuur8ciZ4lRULtnRHd6LZPkdRQFFKNDQC7hIHvK
  template:
    metadata:
      name: mqttui-app
      namespace: iot-tools
