---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ring-mqtt-mqtt
  namespace: ring-mqtt
spec:
  encryptedData:
    password: AgCCcaIu2olJU8DYpC3rmCnkZSsOzysjXEZqBhW9RNT1gMHTp4/ZWgEGdZnvsSh+cgCNu/OTtgvc7ygYeemmBtB8cv/knUhJTFB08vqmPBmNr1Fpj2RxGhx9EWzg0dwyy8DpLNymn0F22NHPTekPiKT8d9QXyVOgtwibpJQ3LrUqPif9iaoIDlW6ruOsOyNkJPVdN7lcWfML//jtL54l8iMLpOow9NG+6t65OwGirupsg03OSYbjdG1Ne8mpJSFMloCNWnfE6kdBuzDuwH9yhjA6qty+KopZ5jwdfxxzCprvtQ3Z3wH+HTn2kz0miuF87jMdwV7+5Via9tQQ/JSU30A9Ro5S+Go/rVAJUrUjsjUVACtKBuVKiw6chTVCV1+F26mdbmLUtdkasFjbr/slLisbsgucJtpJMW4Gv3rTFXXAzInfh4M6enq2OQF4xWSNwp1LiV49gychH7xGkAo+JP9GUpo/K6PuUV7nl9MyktsfGYGZunA1QLoVvz447MkhSHKG8c63aRdRIl/VaT6bta5u1MSoM9wt2TzpINHp52SzCmRPMPSLainRZqkC19vK0nS/ihOpFYHe7dTWEE9JUWCvR3E8UUA9E0k2lHOPv4zj5qHIJQYKQnpPX8iBvUwquLgiXZkDfsp9OY6uy8eLX8+O0OHW/ruT8hXO1IfLd7ZEuUAFc/yy11Wjs4bzBUqYswENbgAf
    username: AgBfoeiKHE97RZBMUAXeuqg+5571BcavPsx/G2yMDBUWVMoriNk6se9I864V9YzorI0LUD2XtwI9YQ1864hNC+3rA441pH/XeOxSI8Mswb27tlCqfnp7TQJIaq9iz0SKBBsj2wGGQKma0XCi0V6FJ/6J9FSwwvMQFosbSnT8Uwaqepen34OeLjWRaR6oaKPKhnIVrX6Ih0HSlbq0q4Wzd4CSgGVvntjHD991VqhEQViS691oAhK8DFnUxb51tFDKPnZQsR1+JTsp3NhSsr1BZNS9eQ2DSHXAuWSklbLpGReX7/+VajDHmc+sVRmOuiLIxQtCQ15oVWejVz6PauMRft6vWDfKC77BxcjEAN2SKIfBuf4O27TvofR4f23E8qMv9uUl2mhAyIhtUlQcG4kbPmVjbZsMR8iMEhsXuvUotmdMddwD+BBuJVFvm1Bm8YSJf9RPW/YnWJx/Drxfjw7sZth+/JNoSsqZzzyQUarBATdG/xCCNu6dZejqwBuwwTXsNXMgZnX2dRYHTgl7bpHEl1iZ+Q5tPaRiLC0iSwq5eti2uzwPVWNCwR7Lt0hN91cqI/3abZzwCpocMeiC1gpKvuBDFXGNUaLQWQypOp6pYv6bo+gYMed0z9e7L9AD7Z/bfFBhbKNnYOWyBO3X7Q0rv3fmBn1Qy7HrA3h8WSfs45STtw36QKZw27Av9YYf0JpqtWH2z7JU
  template:
    metadata:
      name: ring-mqtt-mqtt
      namespace: ring-mqtt
