apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gha-runner-secret
  namespace: gha-runner
  annotations:
    moonrepo.dev/skip-local: "true"
  labels:
    app.kubernetes.io/name: gha-runner
    app.kubernetes.io/instance: gha-runner
    app.kubernetes.io/component: secret
    app.kubernetes.io/managed-by: argocd
spec:
  encryptedData:
    access-token: AgAT+219kW6i6yjRBf8DlpjE0Fe1zckMEz8Dda4ixkrDl7grKloeHvML9JTu4nXzqJUFc/UpEmmu/utzju0p3Kh2kcrHaYI7H6SnoyDfYHDi9ZlZiD5vwTBCmPzqoDjJ4pZoNVW1anCKy4y+LG8kGw5bCi0/kK7yUW5fsWQAZ3gjNh6dd11WXCHrRbAV6MVHsv1L8yoK78kkfHXJDSdn+RD0szL1OcbkHXlWBZml2ORHVtgh/zrqKuLPTkVQgujqfEO4/QcEecZnI63VxKLrpSSVqkRYta2GaTtQ2nyp6tP5VQF5vh4SYZDDqFZHTs9eFu5ONcI6KFY6FZKTJmkJMc+NGYu4BRYjk/Wz8/LJgxso683Y6HRXqlzX4DZIbCnGrwk1tmkBsLDxsyXGVRwXYLhxl8gv+U5N+cl5zf9MeS64OrQXUwts8C0ONTfjvWez8a3AXC/1CRSyejIqa5vnidAYdoOHyfry+8hN2x6aJXw1NVvhKTbF2Z4X8t1gouw1gZ/AcuhPbiHyCh8cChVYQ6KhJ2R/iFLS7uc653IJTft3MeU5TLMDJjmleJzYmYJS9476USLTL41exQPERRU2rn2O6ZZ8JIWgnGUJCnA01aTNqwuq7Q+Ewe1arvOPu6Y4dmKHLXvfmo0iMvjzvQ7ssOG8u7swH9LmEHEMtiai2xWTDHZDgWjDdUMBcW/I4nuIVoPS18rByiSzPVdxNABIil97WLqq+1EM9ZCYnJ0T5k4ulOgCsJnNihoh
  template:
    metadata:
      name: gha-runner-secret
      namespace: gha-runner
