apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gha-runner-secret
  namespace: gha-runner
  annotations:
    moonrepo.dev/skip-local: "true"
spec:
  encryptedData:
    access-token: REPLACE_WITH_SEALED_VALUE
  template:
    metadata:
      name: gha-runner-secret
      namespace: gha-runner
