apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cli-proxy
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    moonrepo.dev/skip-local: "true"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/binary64/moonrepo.git
    targetRevision: HEAD
    path: infra/manifests/cli-proxy

  destination:
    server: https://kubernetes.default.svc
    namespace: cli-proxy

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
      - SkipDryRunOnMissingResource=true
    retry:
      limit: -1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
