apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-crds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    # Skip in CI - webhook with 0 replicas causes issues
    moonrepo.dev/skip-local: "true"
spec:
  project: default
  source:
    repoURL: https://charts.jetstack.io
    targetRevision: "1.19.2"
    chart: cert-manager
    helm:
      releaseName: cert-manager-crds
      values: |
        crds:
          enabled: true
        # Disable all controllers - we only want the CRDs
        replicaCount: 0
        serviceAccount:
          create: false
        prometheus:
          enabled: false
        webhook:
          replicaCount: 0
        cainjector:
          replicaCount: 0
          
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
      - RespectIgnoreDifferences=true
    retry:
      limit: -1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
    