apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudnative-pg
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
    argocd.argoproj.io/sync-options: Replace=true
spec:
  project: default
  source:
    repoURL: https://cloudnative-pg.github.io/charts/
    targetRevision: "0.27.0"
    chart: cloudnative-pg
    helm:
      releaseName: cloudnative-pg
      values: |
        crds:
          create: true

  destination:
    server: https://kubernetes.default.svc
    namespace: cloudnative-pg

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m