apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mariadb-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  project: default
  source:
    repoURL: https://mariadb-operator.github.io/mariadb-operator
    targetRevision: "0.41.0"
    chart: mariadb-operator
    helm:
      releaseName: mariadb-operator
      values: |
        ha:
          enabled: false

  destination:
    server: https://kubernetes.default.svc
    namespace: mariadb-operator

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
