apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pulumi-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://pulumi.github.io/pulumi-kubernetes-operator
    targetRevision: 0.28.0
    chart: pulumi-kubernetes-operator
    helm:
      releaseName: pulumi-operator
      values: |
        operator:
          serviceAccount:
            create: true
  destination:
    server: https://kubernetes.default.svc
    namespace: pulumi-operator-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
