apiVersion: apps/v1
kind: Deployment
metadata:
  name: hasura
  namespace: hasura
  labels:
    app.kubernetes.io/name: hasura
    app.kubernetes.io/instance: hasura
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: hasura
      app.kubernetes.io/instance: hasura
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hasura
        app.kubernetes.io/instance: hasura
    spec:
      nodeSelector:
        kubernetes.io/hostname: vmi3137202
      containers:
        - name: hasura
          image: hasura/graphql-engine:v2.48.13
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: HASURA_GRAPHQL_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: hasura-pg-app
                  key: uri
            - name: HASURA_GRAPHQL_ADMIN_SECRET
              valueFrom:
                secretKeyRef:
                  name: hasura-admin
                  key: HASURA_GRAPHQL_ADMIN_SECRET
            - name: HASURA_GRAPHQL_ENABLE_CONSOLE
              value: "true"
            - name: HASURA_GRAPHQL_DEV_MODE
              value: "false"
            - name: HASURA_GRAPHQL_ENABLED_LOG_TYPES
              value: "startup, http-log, webhook-log, websocket-log, query-log"
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              cpu: 50m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
