apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: hasura
  namespace: hasura
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: gateway
      namespace: istio-system
      sectionName: https
  hostnames:
    - "hasura.brandwhisper.cloud"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - group: ""
          kind: Service
          name: hasura
          port: 8080
          weight: 1
