apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hasura-jwt
  namespace: hasura
spec:
  encryptedData:
    HASURA_GRAPHQL_JWT_SECRET: AgBAb6NZZH6uwaZ39x578tzE+SObrk9Lu+RhyjCIZk11HhwS1OHLiOiRVloTQ+mZjYaZprtEWSge4aE3+/KcozdoQXrYpp4SZjhW2l9y0ayPQpE0PQDAEo9jzkJ5nI7tUwj2jx3tjalvhARNaLY08CGYSel1ykNPyfmNNZWO1R5QOEABd4Dq0vOBQAphSesuKTofw5rwrkv9HphVvLF6Xp3JBMRpu0xYs4QIReJKmoagc0u67rau1lutRf8VmE7Qjs3TVPceunWKEMtCJ1KZUkMIP6N2x2J/7CEINyi/BAKSMptbJRBH2Wi6nhd/6PF3JCe2DIoz7Wx2rIh8LiJHp17ONML4RXF1NW0MpHuqQk8TzFFboFjt+8bnTXjvJMlgKXZg7Id0NhNC0I6XKObgmjDTleGfhB8tiMIjlAVjzYM6wDFr1iZsveiKISZC75m8L5/94EvJ4ruVX4+mb2rTyJmurEg1e8WbYvwCYlnREXmQf4BjXpYIewwKUHpiBgwoRZPaNMN3pM3nJAQrOaz5KoJlixiY44luvqD/dU3MawT1FYnv7E2e0GlSL2ilc2XxfuuLg3nqGiNGO+2m7VIwnOXXY2wadZ0MT0SkG08Xw2Urfo1DQqHjEQAS0phHaHCTZTamb9GEgvF+zQ7xQqxPiktja37PUQgRQ2z7S2w04dtk+nlF+0F+eRgwu4pN9PMpRaQGCSFqd5Q5IwzdqXL+06sshU0Rbowh+U42SEKSHYHCve3iCqorogY4n/WY8wS5TTyJAyAaEo2Hxj3WyM/ZlCAQHD0Ui+Aii0chexPvketibA4G5edn/gcI4g==
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: hasura
        app.kubernetes.io/name: hasura
      name: hasura-jwt
      namespace: hasura
    type: Opaque
