apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hasura-admin
  namespace: hasura
  labels:
    app.kubernetes.io/name: hasura
    app.kubernetes.io/instance: hasura
spec:
  encryptedData:
    HASURA_GRAPHQL_ADMIN_SECRET: AgAOe7XXj0OnJaWsVizHCXx5EQ+ZpckELzC2gyH9bal+b8A/4UC74DblupqPonDLk4De3oxkeF1c1yHJKRIKxP5MHHcv7XyeMuvhFo+D0XMHGN7ZrmWOyELIwBEIOOxS2SfNmkosvo14c2rHnZW/LZ1edWYvqWKy5AdBzQaRd4vUA5E4aRLoASC6jRofeMHT/tFfEVsHGI97/igtQDnISy3P2G2qkQFXMaYd7E+pIwAfZpjuHWS7QTnqeAvnKTK4s/6sVmc1FHagwPjosypeXN8qYyg4vebBm/tPeUkKtKJhb/P65Gf7swdktkY8K8pUzMCoNP8jEb6Y4Fmz1nJ1Oh7cQ3Q4dZFuyMz/lBIOw88k4TyT74SgwcsFBW/dnuxg+cwYn7kpDwceCQnX3GDaHrVjxzwM1E4xnijcZXlOiLFUAb4ppYDUzjSChr6wR2RiguL4FKqOcO5sX1tCk/Gzhk9I8tcNZUiKZKMMWx/RUpjbvffntXKtDAeYpflLUnq5k5QAbExuT6KdVNC5EHso39sidtiw35MaZZZf6aCBFTWkmvXMaLhIH2IpOGG3ABzKkCY8VteZnHmqH9cj0xH4scL2aT8oV55Ms5/e4MSJuZOeYQ08M2Y+WoPE3D/oqzqUCbwGJBoSmmnYOeXKKkWxZ4o/IBj0RYWf5IOnr8HJrANuNP1Z0uWL78OnSI3MLNEphNBXFEarymcYqjMZscDmYv/PPb/Qjxvl27WfZwLkN/Tpzg==
  template:
    metadata:
      name: hasura-admin
      namespace: hasura
      labels:
        app.kubernetes.io/name: hasura
        app.kubernetes.io/instance: hasura
    type: Opaque
