apiVersion: v1
kind: ConfigMap
metadata:
  name: frigate-config
  namespace: frigate
  labels:
    app: frigate
  annotations:
    moonrepo.dev/skip-local: "true"
    argocd.argoproj.io/sync-wave: "2"
data:
  config.yml: |
    mqtt:
      host: mosquitto.home-assistant.svc
      port: 1883

    go2rtc:
      streams:
        front_door:
          - "rtsp://ring-mqtt.ring-mqtt.svc:8554/5c475e55fb69_live"

    cameras:
      front_door:
        enabled: true
        ffmpeg:
          inputs:
            - path: rtsp://127.0.0.1:8554/front_door
              input_args: preset-rtsp-restream
              roles:
                - detect
                - record
        detect:
          enabled: true
          width: 1280
          height: 720
          fps: 5
        record:
          enabled: true
          retain:
            days: 7
            mode: motion
          events:
            retain:
              default: 14
        snapshots:
          enabled: true
          retain:
            default: 14
        objects:
          track:
            - person
            - dog
            - cat
            - car
        motion:
          threshold: 30
          contour_area: 10

      esp_cam_1:
        enabled: true
        ffmpeg:
          inputs:
            - path: http://192.168.1.11:80/
              input_args: -r 5
              roles:
                - detect
                - record
        detect:
          enabled: true
          width: 800
          height: 600
          fps: 5
        record:
          enabled: true
          retain:
            days: 7
            mode: motion
          events:
            retain:
              default: 14
        snapshots:
          enabled: true
          retain:
            default: 14
        objects:
          track:
            - person
            - dog
            - cat
        motion:
          threshold: 25
          contour_area: 15

      esp_cam_2:
        enabled: true
        ffmpeg:
          inputs:
            - path: http://192.168.1.41:80/
              input_args: -r 5
              roles:
                - detect
                - record
        detect:
          enabled: true
          width: 800
          height: 600
          fps: 5
        record:
          enabled: true
          retain:
            days: 7
            mode: motion
          events:
            retain:
              default: 14
        snapshots:
          enabled: true
          retain:
            default: 14
        objects:
          track:
            - person
            - dog
            - cat
        motion:
          threshold: 25
          contour_area: 15

    detectors:
      cpu1:
        type: cpu
        num_threads: 2

    database:
      path: /data/frigate.db
