---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: frigate-mqtt
  namespace: frigate
spec:
  encryptedData:
    password: AgCUZxa7lwV6Hpze6dm95PodXqspopuFJ2iuki1tl0qsAPcooLjT/A6W0pRonsp1lWi2Pd/jLcTeGP5eU+tv47k0Hpb7/J3cHP1zIlljCNfSRvB4SUxdtCH7OcNkaYQ6nhkFlPN107igA32utCyr2Et2hvz88tpzlLoTckqvlQbGeES9zGqPVtZo1EOpLO1I2S9Wzj1kL/t36a4ykZd9L4mA7zX1OSmAaRghELV8uEH8gk+7WzOd+gu2sK+SWVGWvUy6s4RVgUm4KC5DKLZhL1/s7PzP79u0njCCVsnQtlGrqNKrrUxz/wVYf04/sLJgdzsohgbWj3/R8+Hi1WuBeSlRWFgUuSZi7WpHt9ALIT2NngHNXQ2kBmfRwb5ZNLptf+PlhROOOU4doSkt39gtxmSh+TrQV+8vNi9hYkd7z5nw3WEUB3W5qlwcD+PCtRFVZljaTnFesacly8IfizJePPx0MSFpfZcj6ok/vR/9FQ0HtMg9vr5ShhRRnlIKM8J6Zxopg4sGq/JBX7YfmU6OIWVl6z8n8BK8ve2UXB5oU22C24O/yaU3lXGsSFjHZWmGgLkV0efFPwdGel5J/VGMFnRX+9a5hAKQhf5GS2FjFk1umt46wwowjoCgiZCxIiNGMjPJBMcj14OdWsrTEwRoduaA8lSVxjKC6ALXhFXtkvZMZgzB6t17X2Sq4wqNXnO0nMv6RgVe
    username: AgA/zty5btFLTfrKN2MQukyx6CY8UOYbbTqJtUDAII5mCWNAO0DZ9wUa5aKTNTUEgfkR+5czwUw7C6o7L/6j6MqYzf+OBu1GUxPsq8iMNE8gYy2DalQ8qcWnVlVY6JwfMXoNVX6zG1TXW6wcSJclUlzCZUMXzApsDxs2rHnOzt0vv66iRMlCKQXkmkMhagBff9HSjU5q004d0r8kclBsL5my/SccijtQ2lfDHpJ9LC8SRMEFQdJpzoLSpKMekLXxhZ8Sa4XAzD3fHYYwQnBbe/M+ZFGG7m5LJ0Sc6msk7BZb7921q2fnlLTUqDQsMFwHZXUsCcZryfy8MRJR1t5eifqr6nT5ZwS55LNQ8RtPFWp3fTtiaDCEotaMizX03T5OVR9oovMmG6yATddXiXeZy9sBajO0O6IQLySDc9BasDRSmFsmTR4HCvWXAr737Hg3ZrarggSWJDDamPiWfvGox76WVIxlifO7fZREjjpnIdNfTx8sgTAP9FHLsrzTXg/NH5s5/QK9S3kh0YUHvYAP58WWJ25quFDBKvrCuWob8lZwDMwzxHdBsfmUNkWAHZsTeLwu+7FcZcMDJe4Lcl/aVLFf22pAY+Bgnj5BTRvIm4ovF3Pa0/4QnOKy+ct7IpnIos9/+301rPfVmbEGtOVztHbdNqGFldSDJjMBzbLhRy1Vl0UyelFB3muwdgbJ9ybAz916nSLj
  template:
    metadata:
      name: frigate-mqtt
      namespace: frigate
