-- Durable record of every aired DJ utterance, surfaced on radio.brandwhisper.cloud.
-- Mirrors radio.play_history shape. The mp3 itself is archived host-side by
-- radio-tick (dj-clips/<clip_id>.mp3); clip_url is an optional public link.
CREATE TABLE IF NOT EXISTS radio.dj_utterances (
    id        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dj        text NOT NULL,
    timing    text,
    artist    text,
    title     text,
    chars     integer,
    clip_id   text,
    clip_url  text,
    text      text NOT NULL,
    aired_at  timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_dj_utterances_aired_at
    ON radio.dj_utterances (aired_at DESC);

-- Hasura connects as the 'hasura' role; it must own the table (matches the
-- other radio.* tables) or GraphQL queries hit "permission denied".
ALTER TABLE radio.dj_utterances OWNER TO hasura;
