substitutions:
  name: triang7
  friendly_name: "Triangulation Node 7"

esphome:
  name: ${name}
  friendly_name: ${friendly_name}

# ESP32-S3 — loft node
esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

packages:
  common: !include packages/triang-common.yaml
