apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: radio-web
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/binary64/moonrepo.git
    targetRevision: master
    path: infra/manifests/radio-web
  destination:
    server: https://kubernetes.default.svc
    namespace: radio-web
  ignoreDifferences:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      jqPathExpressions:
        - .status

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
