apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  moonrepo.dev/skip-local: "true"

commonLabels:
  app.kubernetes.io/name: pawpicks-stock-checker

resources:
  - namespace.yaml
  - cronjob.yaml
