version: 3
endpoint: https://hasura.brandwhisper.cloud
admin_secret: ${HASURA_ADMIN_SECRET}
metadata_directory: metadata
migrations_directory: migrations
actions:
  kind: synchronous
  handler_webhook_baseurl: http://localhost:3000
