apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: socks-proxy
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/binary64/moonrepo.git
    path: infra/manifests/socks-proxy
    targetRevision: HEAD

  destination:
    server: https://kubernetes.default.svc
    namespace: socks-proxy

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
