apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik-postgres
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    # Requires CloudNativePG CRDs not available in CI
    moonrepo.dev/skip-local: "true"
spec:
  project: default
  source:
    repoURL: https://cloudnative-pg.github.io/charts/
    chart: cluster
    targetRevision: 0.5.0
    helm:
      values: |
        # CloudNativePG Cluster configuration
        # See: https://github.com/cloudnative-pg/charts/tree/main/charts/cluster
        
        type: postgresql
        
        mode: standalone
        
        cluster:
          instances: 1
          
          # PostgreSQL image will be auto-selected based on type
          imageName: ""
          
          storage:
            size: 8Gi
            storageClass: ""
          
          walStorage:
            enabled: false
        
        # Backups configuration (disabled for now)
        backups:
          enabled: false
  
  destination:
    server: https://kubernetes.default.svc
    namespace: authentik
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 225
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 31m
      