---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: external-dns
spec:
  encryptedData:
    api-token: AgAGLVyKoL13z8PM7dzzJX0yvotNgGgncGLhKnWCywfzu7z2CT7X3/XL/xBhKGjqE0GH3/R6JF6Redr30rScIl66hmWQapxL5Q+LeotslVpuMrZOg1EL+oKVkWspdGv4PQNHn3al0FFHhMeFn7qJryb3Or+VDsi3Gk/UhDX1l1VaWkx73QLoQihJ+KVXTMivAgizvLM0rPBkqmTroFgJALpD+x9nF0RgNx7XtG5Jj12u36JNQBxd7pNCH9MdiXsr8j/lE+U5GQ43qMsMb96rYp2VydSc4TzGOeeZqADImdXRIlqbpDm7s73uFMW+tHBj1IndEswoqtC5QrOdX0tLGdL1bzTvOlL3tCIqQdkIMLWFZ3lqFJPV/NHeS7xKoaGLWMjSwTZi4bt93RhfK755ONy3D8O2yKrblW3uzIfZUkIJ0kxoiJ+MRufgb2NANS0lwjqiBEgtCZWl/NZQgfqr0UgqR7pDyADZNmsj4bJuwhFjsPYaAoX5F9ofcbWbc+7yahFU+GG7GmJgAyb13wud+qLwrWkqDYcsURwKKONrxIQUh8uK+g5WHnIx+BXZNHlkryVz21keDblXJyP6FDFAlIwfNwHuAoieGeF9Z0aAxS9SqfVsoskb/TcS89e5YIPKjSPGSIgdro5/I3ari76rXXkmVVSQtp73qHVDP7J6taywTD2TxB9IlhzYbax/ZMo89YNlGajdapPBJlK/h/aMnwgaKKP+D6OaJazqjeY1IGlnQQ6bEHrd0hhO
  template:
    metadata:
      name: cloudflare-api-token
      namespace: external-dns
