apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gha-runner-secret
  namespace: gha-runner
spec:
  encryptedData:
    access-token: REPLACE_WITH_SEALED_VALUE
  template:
    metadata:
      name: gha-runner-secret
      namespace: gha-runner
