---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cli-proxy-api-key
  namespace: cli-proxy
spec:
  encryptedData:
    api-key: AgCRezmKS1sUmx/N+jcHU2jtNwiEAR26Nt3ogJVAuXG2QAgGl4QMX5iIVPz/XB+NbWFiQfXTY+SsYQi7NOsI7I/18OuCwDSot66LMFZHQNSjbEvOSg0nWrqJJusmDgQaorEWlZ2G+6dPL1ilxGdDRPrWjFrhQTwVx+DeTiK/UVDDZ+Rdcct/PSp5HfScQrD0qqRtsYpUylleTswea/bB6xk+cqeVS7bZTwDYpmMAOcM2VADNLT2NK4qBFu4xkaH2mIWpCSe754XhLsPk4r/5ktYsYMWwqSFpseS8saDYeEo93M72/9iiN5V2FpR+a+QGauR7QSV+/l6z6Z9Em0HJKrNUBNZ0B1vojbLDqX+nbRNoEqD+gElej89VzsPv/wX7GDEmxP4UfrnIqq7fANdL7r15ipuI+MNfq9glN7a5ghpWlrHmsTCpOXklSH00maRPdsiD+l+bTtDwVSmgT8t4hiDIhuLg2iDirjbDaZzUCOjw9CYDrwr3paSJcW3M7H0l6k7NVzLGCGQ6Ju49H/jC1ZvinJOEgs6IP0FHiaoIxzBQLYIKluxfjrcDYV72ZHb4s+8/1Ct3sKBexycr2XMq6WSB1NfJ9tT9J/anAlIQ708xJ6FQf+L877hMCVb6cM48aJlWHcq5edX21s5nnmcIKrwOyhibOkazUF9ZA5PQdyZhDD8zXa8s17Z49DqEHrnyNP0UElrbSG5N0cKqHyqHbu2Vt4txJRIYsCZQPmIobd8Yg12JDgbXPrtwUREsUofouMJhCq6ho1O7qaWn8OKcyx2OJ2JE0fk5GJZHIWtf5+YcuhoxpghcR/M7qiJ5B2GdMrHXXQZm1dK3SYGrCVc=
  template:
    metadata:
      name: cli-proxy-api-key
      namespace: cli-proxy
