apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud-db
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
    # Requires Percona XtraDB Cluster CRDs not available in CI
    moonrepo.dev/skip-local: "true"
spec:
  project: default
  source:
    repoURL: https://percona.github.io/percona-helm-charts/
    chart: pxc-db
    targetRevision: "1.18.0"
    helm:
      releaseName: nextcloud-db
      values: |
        unsafeFlags:
          pxcSize: true
          proxySize: true

        # Single node deployment for low-resource environments
        pxc:
          size: 1
          resources:
            requests:
              memory: 512Mi
              cpu: 200m
            limits:
              memory: 1Gi
              cpu: 500m
          persistence:
            enabled: true
            size: 10Gi
          # Disable anti-affinity for single-node clusters
          affinity:
            antiAffinityTopologyKey: "none"

        # HAProxy for MySQL access
        haproxy:
          enabled: true
          size: 1
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 256Mi
              cpu: 200m
          affinity:
            antiAffinityTopologyKey: "none"

        # Disable ProxySQL (using HAProxy instead)
        proxysql:
          enabled: false

        # Disable PMM monitoring
        pmm:
          enabled: false

        # Disable backups by default
        backup:
          enabled: false

  destination:
    server: https://kubernetes.default.svc
    namespace: nextcloud

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
    retry:
      limit: -1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
