---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: home-network
  namespace: external-dns
spec:
  encryptedData:
    public-ip: AgAXiF1JVYslIJylTpioAGjEov9Ar5UcdU3jsFUunFJMBDaXrC+jQ8BfKCnavvGOV0/uv4esIX2aJv5lL7kTQ4d5CvSz3Ri0tbzzS5Sg9RS9YKtWvkWgV6N71+mZgkDpNnDqCTixCoIclofXzUdlzTWzyatDvj4EsAbdgSf4CZRoxDmf0z19BXh9JhRAIf24/BfpgT6f+oHNdRq00bokr0HCyYjVwxJsi+CwUEnY8qP7aHFKJVfy3NNAwJIxS/xCjp9QSSCseInJ6HfaOIDYiMcE2uwgA7jGAjmrniNvkXb+9Ji7v0lPczqj/Tn3gVfhoyIWwD8BEBs+8MbK8Yyp9iZ1LnCDWbKkYeH/6IDSAZCfKSR7NvOxEqxnPmNSP6MtjmvF9Q3mHCa9nU9OeT3wDd9BW63mS3w560MKxfS9pUswYRDmRGHZKnSXpok3yRzeZvHrbNX7bA0BZ+2fyVQ2PthXOTHa8q2lURNBdzZWl2l4B2z6EjuC0dXDr0/59aEN8Ea031TKXkrrn07ToEIICN67zWWOZxzjAqy6CBP63mPScECjA7vT41cBUbowKxpPJhaawNFAzDaTYyhjB0DyTbZ99iQC+70IqKGFX+lEV8LHu3s1fK01xZHsoM8PEvpcSlrQtlkbhnpqABBa+u94SPRJWKBNscr2bX1eTN/hG3wTZmoAPYPFSmhPEqqbeziLck27HT1gNcMK+X2q5WQ=
  template:
    metadata:
      name: home-network
      namespace: external-dns
