---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: home-network
  namespace: external-dns
spec:
  encryptedData:
    public-ip: AgC8zeP/Ue3+OiQyafxodcEWIoMz35K0YRySy8y7vL3gDvb4YU1+exPm6TvHDIl5P4TXRio7xhGNLlVk7tP4g2um0I93qZdRzc0dHsNiOYDG8JIohmkFegHcau8pPZ1Xa9X2O9gCsz8oKPKS2RSOw+s7FYIBhgs0pVm+NJfGmI8GwZtQiJCO4yNuYH2npL5WeYVOJ64uaYxoqV58H3bNHgcwesgxXcwW7+3/6/NO4/eRFJaZn8xn35TolgA4RMJhLGuU0y18olR7MMRGMp2SThbUdDxg+ET5zCzsTj/B+SJAsKHMjBzC6v3B0yHmxMTjSJsR+wcnmpZe1hq1uFWM139Fw5mZ3eOW8ozkWVrcmw3rldCMTBhJ9pe+v/42m2h99XWV1F7LoGyzhtK4/63koy5kaC5dK48RcXi/2XDF65X4+NLRpPcaY8tnoTYQx5Sk8QYWWcWMMlfssrps5n4Ac/lX+zwPWo3soO2uGbTY3BJW3VwM60rh2UUge55aEnf/7xcUtv/NQ4svpJZumCy37eHKQebId0jsIhbeOw8ER8WYn4byoLTwvsr4Ij0ccSfCavrcKq6MCyh4rzZrNarT14p5NuDSNw4WMgMOGCzo73HNWZMKLuFDJBxzBm3ueofaS700mvXZd5+cn3gTDTSKDfZi2ePNrCZWUG4NpG4ENZWnimyw2YcuSofzUVq9S8ePpEFyx5cfeFIaycSAiw==
  template:
    metadata:
      name: home-network
      namespace: external-dns
