apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mosquitto2
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://naps.github.io/helm-charts/
    chart: mosquitto
    targetRevision: "1.0.4"
    helm:
      releaseName: mosquitto
      values: |
        fullnameOverride: mosquitto
        auth:
          username: mqtt
          password: mqtt
        mosquitto:
          config: |
            username: mqtt
            password: mqtt
            
  
  destination:
    server: https://kubernetes.default.svc
    namespace: home-assistant
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
      - SkipDryRunOnMissingResource=true
      - ServerSideApply=true
    retry:
      limit: -1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
