apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  parentRefs:
  - name: gateway
    namespace: istio-system
  hostnames:
  - "home-assistant.localhost"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: home-assistant
      port: 8123
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: home-assistant-codeserver
  namespace: home-assistant
spec:
  parentRefs:
  - name: gateway
    namespace: istio-system
  hostnames:
  - "hass-code.localhost"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: home-assistant-codeserver
      port: 12321
