apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: home-tls
  namespace: istio-system
spec:
  secretName: home-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames:
  - "home.brandwhisper.cloud"
  - "*.home.brandwhisper.cloud"
