---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gateway
  namespace: istio-system
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  gatewayClassName: istio
  type: NodePort
  listeners:
  - name: default
    port: 80
    protocol: HTTP
    nodePort: 30080
    allowedRoutes:
      namespaces:
        from: All
  - name: https
    port: 443
    protocol: HTTPS
    nodePort: 30443
    hostname: home.brandwhisper.cloud
    tls:
      mode: Terminate
      certificateRefs:
      - name: home-tls
    allowedRoutes:
      namespaces:
        from: All
  infrastructure:
    parametersRef:
      group: ""
      kind: ConfigMap
      name: gw-options
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gw-options
  namespace: istio-system
data:
  deployment: |
    spec:
      replicas: 1
      template:
        spec:
          hostNetwork: true
          dnsPolicy: ClusterFirstWithHostNet
          containers:
          - name: istio-proxy
