---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gateway
  namespace: istio-system
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  gatewayClassName: istio
  listeners:
  - name: default
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: All
  infrastructure:
    parametersRef:
      group: ""
      kind: ConfigMap
      name: gw-options
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gw-options
  namespace: istio-system
data:
  deployment: |
    spec:
      replicas: 1
      template:
        spec:
          containers:
          - name: istio-proxy
