---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: matter-hub-secret
  namespace: matter-hub
  annotations:
    # Unseal the Secret before the Deployment that consumes it via secretKeyRef.
    argocd.argoproj.io/sync-wave: "0"
spec:
  encryptedData:
    ha-token: AgByaRpvvq+84qQCvXGzRTsY/SNhKEgAyIkDjaILaLgDOnikW+1wHKINVB1v4MphfR/Akt8oAaNJIAApey+Dy4wYBasQubDu2IixpSwRG2Nh7ZZRRa6X2YydhOr0vWdF4n01o0KdWKiaLD4RxuidES94b58nB+a+D/hQu0zt7IaKQXgnCHM5iWDeexfmYPgftlgIAvktzAUKMZSlhcs+lcXqrSRHKSTKGg4XmbwEzWVNWkF6l9XeddCNREKhxr/sAEnAoz/zdgPyW/UN/RT6L2EGBjpZY3EGkXYRCP7vOcJV6fabSZ5Eagob8HdUDVnB9WGD9BMiN3f9rfXby7xNRttPEnecYAnYi4Gp/mtqp5pAcsrfdmDQaHvuaNNP4+DmGMZDOSQ+jyn0gr3b/NScidMy1wqFyjHAUwedfJ2Dzg25Vf1O8oAPhHhGoGpqS59GnzttCwICXWslpyIub2/QD9Ynwvh8EQJgXlqMlxSshjqomHWIo6MRkCseoGhe8gWdP/TBq/enWxSexmagRdwnkdObq38z+cnbuv6T1RfQaZsMwtD6S0U22ZZb+l6cLyIwVy5rEBi/uRq/oRhTEd3hB0v71OTmR7O8Q0DKJTyYP5YLfjluejdyuH17ImSSyuJiQrPKhB6t3JbZpxYGBxJitp3hItf2QEqCSGUJW7bZTWWbhzoConNtgZ1DOVKyPVOw8bFUUTgarSSyooORPHb7pkBiE81MRtxvbjQkReExaP29Czw70D15AW4yvGYwpow6Lxno4tXPPXJu2JOx5oBWaepyf3GlwdzeYVXTWlB4O7q6jr130X/Gq7qCi5FEbhz665c1I992XpyysX062dcoy1RBtIaLmhjXbPO+ULtg5lPAv5j4kpsNsxeW5Pw6KAR9GYypxkyXqlVNt4EjdUb/6MJdOs/dVic345fOpjjQT8WOwH2mTmxijVIF9gYQKg==
  template:
    metadata:
      name: matter-hub-secret
      namespace: matter-hub
