---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: litellm-gateway-key
  namespace: open-webui
spec:
  encryptedData:
    LITELLM_MASTER_KEY: AgAw8JS0TEGXfDHwJeF17Ot4zqFMY2s1MHzmpFNYSjctEZgLxjfjZ1Fzd9HgxKks0miPqkh+gkDPopN7sxHRUkXGRw/2WSyBPIHDULyGaTC5fja+pzDYn2c13zvkuABKzxu/DssdXUfOSbLP/tONss9RPt5XL3ZxMXIgaRJVd/HIfYNq1alqDCTSKktvy08+WWEw7Nzj93J2yf6zORek3yXG3+qaD4wFsXIm+cX3RUBQbizj54ktpY/ug+pPige1bgrfyUqKD/z5VWiWkEidHvC1ur76dQK0jt7ZaVXndsu2uAXk9IPMb4pBRNEJOn8RvEkXws1T9KNNoVwrBgJOc6CC2uvxUZxQhE9fr5ST7e8mwNFv17nYn+OaJqjzzRyXsbMZa/vPVsIjQ0gWHWNJsdLVHwp80THF8n5BrYsrv12AebJQQhvaMeN3wBBkxsGuYERbhIQMWRJxD/N4fkGdSsaSmBkR0ymPU9kP3wqFD0CB3Siy/jPm1k+TvESl6sroo0kQ9NINi+t2pllnR9UE0BVCrx2c2NqnLd9Ln2S9J9KIHpCNeZ8x8CbC11f190dMCDzjBGABy4TgI2bYqF7dzDqLPKFyJtD5Ra3ryFPBaCx08Sk2kEemxYxA3GNeZ4sI2+trlZkYOIaELY9U7C+rUfpM53/Z2lY2ZMd7VsYD+QxYnEeNlAfiWesonD4H+ZQcDnkiPz458i1GPWr7GptosquFp6cbs9M=
  template:
    metadata:
      name: litellm-gateway-key
      namespace: open-webui
