#!/usr/bin/env bash
# Bootstrap hermes host-side env + skills from moonrepo + AWS Secrets Manager.
#
# Idempotent. Safe to re-run.
#
# Prereqs on the host:
#   - aws CLI configured with read access to the moonrepo/* secrets
#   - jq installed
#   - Run as the `hermes` user
#
# What it does:
#   1. Pulls listed hermes-* secrets from AWS Secrets Manager
#   2. Writes /home/hermes/.hermes/.env (mode 0600)
#   3. Symlinks hermes/skills/* from this repo into ~/.hermes/skills/moonrepo/
set -euo pipefail

REPO_ROOT=$(git rev-parse --show-toplevel 2>/dev/null || (cd "$(dirname "$0")/.." && pwd))
HERMES_DIR="$REPO_ROOT/hermes"
HERMES_HOME="${HERMES_HOME:-$HOME/.hermes}"
ENV_FILE="$HERMES_HOME/.env"
SKILLS_LINK="$HERMES_HOME/skills/moonrepo"

PREFIX="moonrepo"

# Secrets to pull. Key = local env var name, value = AWS secret id (without prefix).
declare -A HERMES_SECRETS=(
  [HASS_TOKEN]="hermes-ha-token"
)

# Non-secret defaults always written to the env file.
declare -A HERMES_DEFAULTS=(
  [HASS_URL]="http://home-assistant.home-assistant.svc.cluster.local:8123"
)

command -v aws >/dev/null || { echo "ERROR: aws CLI not found" >&2; exit 1; }
command -v jq  >/dev/null || { echo "ERROR: jq not found" >&2; exit 1; }

mkdir -p "$(dirname "$ENV_FILE")"

tmpfile=$(mktemp)
trap 'rm -f "$tmpfile"' EXIT
chmod 600 "$tmpfile"

{
  echo "# Auto-generated by hermes/bootstrap-env.sh — do not edit by hand."
  echo "# Regenerate with: $REPO_ROOT/hermes/bootstrap-env.sh"
  echo "# Timestamp: $(date -u +%FT%TZ)"
  echo

  for key in "${!HERMES_DEFAULTS[@]}"; do
    printf '%s=%q\n' "$key" "${HERMES_DEFAULTS[$key]}"
  done

  for key in "${!HERMES_SECRETS[@]}"; do
    secret_id="${PREFIX}/${HERMES_SECRETS[$key]}"
    echo "# Fetching $secret_id ..." >&2
    if value=$(aws secretsmanager get-secret-value \
        --secret-id "$secret_id" \
        --query SecretString \
        --output text 2>/dev/null); then
      printf '%s=%q\n' "$key" "$value"
    else
      echo "WARN: could not fetch $secret_id (skipping)" >&2
    fi
  done
} > "$tmpfile"

mv "$tmpfile" "$ENV_FILE"
chmod 600 "$ENV_FILE"
echo "✓ Wrote $ENV_FILE (mode 600)"

# Symlink skills into hermes skills dir so they show up in skill discovery.
mkdir -p "$(dirname "$SKILLS_LINK")"
if [ -L "$SKILLS_LINK" ] || [ -e "$SKILLS_LINK" ]; then
  rm -rf "$SKILLS_LINK"
fi
ln -s "$HERMES_DIR/skills" "$SKILLS_LINK"
echo "✓ Linked $SKILLS_LINK -> $HERMES_DIR/skills"

echo
echo "Done. Reload hermes to pick up the new env:"
echo "  systemctl --user restart hermes   # or however hermes is run"
