#!/usr/bin/env bash
# Bootstrap hermes host-side env + skills from moonrepo + AWS Secrets Manager.
#
# Idempotent. Safe to re-run.
#
# Prereqs on the host:
#   - aws CLI configured with read access to the moonrepo/* secrets
#   - Run as the `hermes` user
#   - hermes/bootstrap-host.sh has installed kubectl + brave + xvfb
#
# What it does:
#   1. Pulls listed hermes-* secrets from AWS Secrets Manager
#   2. Writes /home/hermes/.hermes/.env (mode 0600)
#   3. Writes /home/hermes/.hermes/kubeconfig (mode 0600) for the socks-proxy
#      port-forward systemd user unit
#   4. Symlinks hermes/skills/* from this repo into ~/.hermes/skills/moonrepo/
#   5. Symlinks hermes/agent-browser.json into ~/.hermes/agent-browser.json
#   6. Installs the hermes-xvfb and hermes-socks-proxy user systemd units
#      into ~/.config/systemd/user/ (operator still needs to daemon-reload
#      and enable them — printed at the end)
#
# Fails loudly if any required secret is missing — the agent must never start
# with a partially-populated env.
set -euo pipefail

REPO_ROOT=$(git rev-parse --show-toplevel 2>/dev/null || (cd "$(dirname "$0")/.." && pwd))
HERMES_DIR="$REPO_ROOT/hermes"
HERMES_HOME="${HERMES_HOME:-$HOME/.hermes}"
ENV_FILE="$HERMES_HOME/.env"
ENV_DIR="$(dirname "$ENV_FILE")"
SKILLS_LINK="$HERMES_HOME/skills/moonrepo"
KUBECONFIG_FILE="$HERMES_HOME/kubeconfig"
BROWSER_CONFIG_LINK="$HERMES_HOME/agent-browser.json"
SYSTEMD_USER_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user"

PREFIX="moonrepo"

# Secrets to pull. Key = local env var name, value = AWS secret id (without prefix).
# Every entry here is REQUIRED — bootstrap fails if any cannot be fetched.
declare -A HERMES_SECRETS=(
  [HASS_TOKEN]="hermes-ha-token"
)

# Secrets that are written to dedicated files (not the env file) because
# they're multi-line (YAML/certs) and shell-quoting them is brittle.
# Format: AWS secret id → destination path (absolute, inside $ENV_DIR).
declare -A HERMES_FILE_SECRETS=(
  [hermes-kubeconfig]="$KUBECONFIG_FILE"
)

# Non-secret defaults always written to the env file.
#
# Browser automation: Brave + loopback SOCKS5 + Xvfb :99. See
# hermes/agent-browser.md, hermes/agent-browser.json, and
# infra/systemd/hermes-{xvfb,socks-proxy}.service.
#
# AGENT_BROWSER_* are read directly by the agent-browser CLI.
# ALL_PROXY is how agent-browser receives a SOCKS5 URL — its own `proxy`
# field / --proxy flag only accept HTTP/HTTPS. See the bundled
# proxy-support.md reference.
declare -A HERMES_DEFAULTS=(
  [HASS_URL]="http://home-assistant.home-assistant.svc.cluster.local:8123"
  [DISPLAY]=":99"
  [AGENT_BROWSER_CONFIG]="$BROWSER_CONFIG_LINK"
  [AGENT_BROWSER_EXECUTABLE_PATH]="/usr/bin/brave-browser"
  [AGENT_BROWSER_HEADED]="1"
  [ALL_PROXY]="socks5://127.0.0.1:1080"
  # Don't route loopback / cluster DNS / metadata via SOCKS.
  [NO_PROXY]="localhost,127.0.0.0/8,10.43.0.0/16,10.42.0.0/16,.svc.cluster.local"
)

command -v aws >/dev/null || { echo "ERROR: aws CLI not found" >&2; exit 1; }

# Lock down the target directory first so both the tmpfile and final env file
# live in a 0700 dir the hermes user owns.
mkdir -p "$ENV_DIR"
chmod 700 "$ENV_DIR"

# Persistent cleanup: track every tmpfile we create and rm them all on EXIT.
# A single trap installed once, instead of overwriting per-iteration (which
# would leak earlier iterations' tmpfiles if the script exits mid-loop).
_tmpfiles=()
cleanup_tmpfiles() {
  local f
  for f in "${_tmpfiles[@]:-}"; do
    [ -n "$f" ] && rm -f "$f"
  done
}
trap cleanup_tmpfiles EXIT

# Create tmpfile beside ENV_FILE so `mv` is atomic (same filesystem) and the
# secret never touches /tmp (which may be a tmpfs shared with other services).
tmpfile=$(mktemp "$ENV_DIR/.env.XXXXXX")
_tmpfiles+=("$tmpfile")
chmod 600 "$tmpfile"

{
  echo "# Auto-generated by hermes/bootstrap-env.sh — do not edit by hand."
  echo "# Regenerate with: $REPO_ROOT/hermes/bootstrap-env.sh"
  echo "# Timestamp: $(date -u +%FT%TZ)"
  echo

  for key in "${!HERMES_DEFAULTS[@]}"; do
    printf '%s=%q\n' "$key" "${HERMES_DEFAULTS[$key]}"
  done

  for key in "${!HERMES_SECRETS[@]}"; do
    secret_id="${PREFIX}/${HERMES_SECRETS[$key]}"
    echo "# Fetching $secret_id ..." >&2
    if ! value=$(aws secretsmanager get-secret-value \
        --secret-id "$secret_id" \
        --query SecretString \
        --output text 2>&1); then
      echo "ERROR: could not fetch $secret_id" >&2
      echo "       $value" >&2
      echo "       Set it first with: cd infra/secrets && ./set-secret.sh ${HERMES_SECRETS[$key]} \"<value>\"" >&2
      exit 1
    fi
    if [ -z "$value" ] || [ "$value" = "None" ]; then
      echo "ERROR: secret $secret_id is empty" >&2
      exit 1
    fi
    printf '%s=%q\n' "$key" "$value"
  done
} > "$tmpfile"

mv "$tmpfile" "$ENV_FILE"
chmod 600 "$ENV_FILE"
echo "✓ Wrote $ENV_FILE (mode 600)"

# File-type secrets: write each to its own 0600 tmpfile in the same dir, then
# atomic-rename. Keeps multi-line YAML out of shell-quoted env, and keeps the
# secret off /tmp. Captures aws CLI stderr so failures print the real reason.
for secret_name in "${!HERMES_FILE_SECRETS[@]}"; do
  dest="${HERMES_FILE_SECRETS[$secret_name]}"
  secret_id="${PREFIX}/${secret_name}"
  dest_dir="$(dirname "$dest")"
  mkdir -p "$dest_dir"
  chmod 700 "$dest_dir"
  echo "# Fetching $secret_id → $dest ..." >&2
  file_tmp=$(mktemp "$dest_dir/.$(basename "$dest").XXXXXX")
  _tmpfiles+=("$file_tmp")
  chmod 600 "$file_tmp"
  stderr_tmp=$(mktemp "$dest_dir/.awserr.XXXXXX")
  _tmpfiles+=("$stderr_tmp")
  chmod 600 "$stderr_tmp"
  if ! aws secretsmanager get-secret-value \
        --secret-id "$secret_id" \
        --query SecretString \
        --output text > "$file_tmp" 2> "$stderr_tmp"; then
    echo "ERROR: could not fetch $secret_id" >&2
    sed 's/^/       aws: /' "$stderr_tmp" >&2
    echo "       Set it first with: cd infra/secrets && ./set-secret.sh $secret_name \"<value>\"" >&2
    exit 1
  fi
  if [ ! -s "$file_tmp" ] || [ "$(head -c 8 "$file_tmp")" = "None" ]; then
    echo "ERROR: secret $secret_id is empty" >&2
    exit 1
  fi
  mv "$file_tmp" "$dest"
  chmod 600 "$dest"
  echo "✓ Wrote $dest (mode 600)"
done

# Symlink skills into hermes skills dir so they show up in skill discovery.
# Safety: only replace an existing symlink — never rm -rf a real directory here.
mkdir -p "$(dirname "$SKILLS_LINK")"
if [ -L "$SKILLS_LINK" ]; then
  rm -f "$SKILLS_LINK"
elif [ -e "$SKILLS_LINK" ]; then
  echo "ERROR: $SKILLS_LINK exists and is not a symlink; refusing to overwrite." >&2
  echo "       Move or remove it manually, then re-run bootstrap." >&2
  exit 1
fi
ln -s "$HERMES_DIR/skills" "$SKILLS_LINK"
echo "✓ Linked $SKILLS_LINK -> $HERMES_DIR/skills"

# Symlink agent-browser config. Same symlink-only safety as skills.
if [ -L "$BROWSER_CONFIG_LINK" ]; then
  rm -f "$BROWSER_CONFIG_LINK"
elif [ -e "$BROWSER_CONFIG_LINK" ]; then
  echo "ERROR: $BROWSER_CONFIG_LINK exists and is not a symlink; refusing to overwrite." >&2
  echo "       Move or remove it manually, then re-run bootstrap." >&2
  exit 1
fi
ln -s "$HERMES_DIR/agent-browser.json" "$BROWSER_CONFIG_LINK"
echo "✓ Linked $BROWSER_CONFIG_LINK -> $HERMES_DIR/agent-browser.json"

# Install systemd user units so `systemctl --user enable` just works.
# `install -m 0644` preserves permissions and is idempotent — no need to
# compare contents first, install always writes.
mkdir -p "$SYSTEMD_USER_DIR"
for unit in hermes-xvfb.service hermes-socks-proxy.service; do
  src="$REPO_ROOT/infra/systemd/$unit"
  dst="$SYSTEMD_USER_DIR/$unit"
  if [ ! -f "$src" ]; then
    echo "ERROR: unit source $src missing" >&2
    exit 1
  fi
  install -m 0644 "$src" "$dst"
  echo "✓ Installed $dst"
done

echo
echo "Done. Next steps:"
echo "  systemctl --user daemon-reload"
echo "  systemctl --user enable --now hermes-xvfb hermes-socks-proxy"
echo "  # then reload hermes to pick up the new env"
