#!/usr/bin/env bash
# Bootstrap hermes host-side env + skills from moonrepo + AWS Secrets Manager.
#
# Idempotent. Safe to re-run.
#
# Prereqs on the host:
#   - aws CLI configured with read access to the moonrepo/* secrets
#   - Run as the `hermes` user
#
# What it does:
#   1. Pulls listed hermes-* secrets from AWS Secrets Manager
#   2. Writes /home/hermes/.hermes/.env (mode 0600)
#   3. Symlinks hermes/skills/* from this repo into ~/.hermes/skills/moonrepo/
#
# Fails loudly if any required secret is missing — the agent must never start
# with a partially-populated env.
set -euo pipefail

REPO_ROOT=$(git rev-parse --show-toplevel 2>/dev/null || (cd "$(dirname "$0")/.." && pwd))
HERMES_DIR="$REPO_ROOT/hermes"
HERMES_HOME="${HERMES_HOME:-$HOME/.hermes}"
ENV_FILE="$HERMES_HOME/.env"
ENV_DIR="$(dirname "$ENV_FILE")"
SKILLS_LINK="$HERMES_HOME/skills/moonrepo"

PREFIX="moonrepo"

# Secrets to pull. Key = local env var name, value = AWS secret id (without prefix).
# Every entry here is REQUIRED — bootstrap fails if any cannot be fetched.
declare -A HERMES_SECRETS=(
  [HASS_TOKEN]="hermes-ha-token"
)

# Non-secret defaults always written to the env file.
declare -A HERMES_DEFAULTS=(
  [HASS_URL]="http://home-assistant.home-assistant.svc.cluster.local:8123"
)

command -v aws >/dev/null || { echo "ERROR: aws CLI not found" >&2; exit 1; }

# Lock down the target directory first so both the tmpfile and final env file
# live in a 0700 dir the hermes user owns.
mkdir -p "$ENV_DIR"
chmod 700 "$ENV_DIR"

# Create tmpfile beside ENV_FILE so `mv` is atomic (same filesystem) and the
# secret never touches /tmp (which may be a tmpfs shared with other services).
tmpfile=$(mktemp "$ENV_DIR/.env.XXXXXX")
trap 'rm -f "$tmpfile"' EXIT
chmod 600 "$tmpfile"

{
  echo "# Auto-generated by hermes/bootstrap-env.sh — do not edit by hand."
  echo "# Regenerate with: $REPO_ROOT/hermes/bootstrap-env.sh"
  echo "# Timestamp: $(date -u +%FT%TZ)"
  echo

  for key in "${!HERMES_DEFAULTS[@]}"; do
    printf '%s=%q\n' "$key" "${HERMES_DEFAULTS[$key]}"
  done

  for key in "${!HERMES_SECRETS[@]}"; do
    secret_id="${PREFIX}/${HERMES_SECRETS[$key]}"
    echo "# Fetching $secret_id ..." >&2
    if ! value=$(aws secretsmanager get-secret-value \
        --secret-id "$secret_id" \
        --query SecretString \
        --output text 2>&1); then
      echo "ERROR: could not fetch $secret_id" >&2
      echo "       $value" >&2
      echo "       Set it first with: cd infra/secrets && ./set-secret.sh ${HERMES_SECRETS[$key]} \"<value>\"" >&2
      exit 1
    fi
    if [ -z "$value" ] || [ "$value" = "None" ]; then
      echo "ERROR: secret $secret_id is empty" >&2
      exit 1
    fi
    printf '%s=%q\n' "$key" "$value"
  done
} > "$tmpfile"

mv "$tmpfile" "$ENV_FILE"
chmod 600 "$ENV_FILE"
echo "✓ Wrote $ENV_FILE (mode 600)"

# Symlink skills into hermes skills dir so they show up in skill discovery.
# Safety: only replace an existing symlink — never rm -rf a real directory here.
mkdir -p "$(dirname "$SKILLS_LINK")"
if [ -L "$SKILLS_LINK" ]; then
  rm -f "$SKILLS_LINK"
elif [ -e "$SKILLS_LINK" ]; then
  echo "ERROR: $SKILLS_LINK exists and is not a symlink; refusing to overwrite." >&2
  echo "       Move or remove it manually, then re-run bootstrap." >&2
  exit 1
fi
ln -s "$HERMES_DIR/skills" "$SKILLS_LINK"
echo "✓ Linked $SKILLS_LINK -> $HERMES_DIR/skills"

echo
echo "Done. Reload hermes to pick up the new env:"
echo "  systemctl --user restart hermes   # or however hermes is run"
