# https://moonrepo.dev/docs/config/project
$schema: "https://moonrepo.dev/schemas/project.json"

language: "typescript"
layer: "tool"

tasks:
  lint:
    command: "biome check ."

  type-check:
    command: "tsc --noEmit"

  preview:
    command: "pulumi preview"
    preset: 'server'

  up:
    command: "pulumi up"
    preset: 'server'

  destroy:
    command: "pulumi destroy"
    preset: 'server'
