# Pulumi Operator Secrets Template
#
# These secrets need to be created manually before the Pulumi Stack can run.
# DO NOT commit these secrets to git - use SealedSecrets or external secret management.
#
# REQUIRED SECRETS:
#
# 1. Pulumi Access Token (for state management in Pulumi Cloud)
#    Get from: https://app.pulumi.com/account/tokens
#
# 2. Cloudflare API Token (for Pulumi to CREATE other API tokens)
#    Get from: https://dash.cloudflare.com/profile/api-tokens
#    Needs permissions: Account.Account Settings:Read, Zone.Zone:Read, User.API Tokens:Edit
#
# Create with:
# kubectl create secret generic pulumi-access-token \
#   --namespace=pulumi-operator-system \
#   --from-literal=accessToken=pul-xxxxx
#
# kubectl create secret generic cloudflare-api-token-pulumi \
#   --namespace=pulumi-operator-system \
#   --from-literal=token=xxxxx
#
# WHAT HAPPENS:
# - Pulumi uses cloudflare-api-token-pulumi to create a RESTRICTED Cloudflare API token
# - The restricted token is stored as 'cloudflare-api-token' in both:
#   - cert-manager namespace (for DNS-01 ACME challenges)
#   - external-dns namespace (for DNS record management)
# - The secret key is 'api-token' in both namespaces

---
apiVersion: v1
kind: Secret
metadata:
  name: pulumi-access-token
  namespace: pulumi-operator-system
type: Opaque
stringData:
  accessToken: "REPLACE_WITH_PULUMI_ACCESS_TOKEN"

---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token-pulumi
  namespace: pulumi-operator-system
type: Opaque
stringData:
  token: "REPLACE_WITH_CLOUDFLARE_API_TOKEN"
