# Pulumi Operator Secrets Template
#
# These secrets need to be created manually before the Pulumi Stack can run.
# DO NOT commit these secrets to git - use SealedSecrets or external secret management.
#
# Create these secrets with:
# kubectl create secret generic pulumi-access-token \
#   --namespace=pulumi-operator-system \
#   --from-literal=accessToken=pul-xxxxx
#
# kubectl create secret generic cloudflare-api-token \
#   --namespace=pulumi-operator-system \
#   --from-literal=token=xxxxx

---
apiVersion: v1
kind: Secret
metadata:
  name: pulumi-access-token
  namespace: pulumi-operator-system
type: Opaque
stringData:
  accessToken: "REPLACE_WITH_PULUMI_ACCESS_TOKEN"

---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token
  namespace: pulumi-operator-system
type: Opaque
stringData:
  token: "REPLACE_WITH_CLOUDFLARE_API_TOKEN"
