apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto
  namespace: home-assistant
data:
  mosquitto.conf: |
    listener 1883
    allow_anonymous false
    password_file /mosquitto/config/passwd
  passwd: |
    mqtt:$7$101$fg9bC65TH63ed9nI$e51jMvivZjc/324554wP8xayXX8BK+2NUGKbSSAz+A7uRx1qARNQtqEiDLnbhADMZ7M06BVVx9iq5le4l/GitQ==
