apiVersion: apps/v1
kind: Deployment
metadata:
  name: start-page
  namespace: start-page
  labels:
    app: start-page
spec:
  replicas: 1
  selector:
    matchLabels:
      app: start-page
  template:
    metadata:
      labels:
        app: start-page
    spec:
      nodeSelector:
        kubernetes.io/hostname: vmi3137202
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html
              readOnly: true
          resources:
            requests:
              memory: 16Mi
              cpu: 10m
            limits:
              memory: 32Mi
              cpu: 50m
      volumes:
        - name: html
          configMap:
            name: start-page-html
