apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: start-page
  name: start-page
  namespace: start-page
spec:
  replicas: 1
  selector:
    matchLabels:
      app: start-page
  template:
    metadata:
      labels:
        app: start-page
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: start-env
        image: nginx:alpine
        name: nginx
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 50m
            memory: 32Mi
          requests:
            cpu: 10m
            memory: 16Mi
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: html
          readOnly: true
      nodeSelector:
        kubernetes.io/hostname: vmi3137202
      volumes:
      - configMap:
          name: start-page-html
        name: html
