apiVersion: v1
kind: Service
metadata:
  name: watch-adb-discover
  namespace: watch-adb-discover
  labels:
    app: watch-adb-discover
spec:
  type: NodePort
  selector:
    app: watch-adb-discover
  ports:
    - port: 3200
      targetPort: 3200
      nodePort: 30200
      protocol: TCP
