---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: zeroclaw-env
  namespace: zeroclaw
spec:
  encryptedData:
    API_KEY: AgCpIaZA200PvgQFWHSs1dKnIYJoZxLFq3Q1HLpLEQ12bFM1gfsexAtkL5ZxBYLCjpXCdfw45Twcnp+vtBjoprLpozju/PbDJsuyr9+CcBu7r3rHZmUHq//2EWwHmxQeGWeTJWgQU/5cjh1Ovt8mchy6Ih5sXpWXvYuDiJFpCpxedWk2yHNOg8qGmTcoB19ojX/y3ZJdLvBtgnOPLptwsgT8sxhzdtgq9yy454F8npmZiqTXf++PffqxSpcfDRwDdLRwAvc91AwGF00J/QkmGnryPrxgpT3TXYZYlou9sCdGKswJuK4CgsF/mhILMJkpCdTHKBsz/7ls3llJYJMETvRK+zGdPXkF9FBvNJrGJ6x1xKp65GXpu9cCqDv75neCUVX743c/k3vFxOVdWzq/q4MZc1xI41uf91L+DFtYL/O2BcnTXKT5owMdT/3iFIPDZ4O0ARFxBLzG8+uyNAjAY1F8vXWWzIPM+Nm7erqAgVV0cge19GBhWKb/3tVKfjIerZ+lBvzMOUPyyKvPsJzwD+cDE7EYVfzKuKbnaKRAw411OkbFrypITb3CaJvz24Y64HDVxvqyQBJ/vDghmyvpPERpG4RxdF7xeg8/21eAed/m6aNrkO6HsD3M7r1DK6qzqqEc1q2CY/W9YFj51PiOhrdEDal0RFpun0LvhAA/0ibDWsC2t4OAWOULhbJs0neUMdLuzRO1kzYyUGMohEb7QaP8ucqt5T8=
  template:
    metadata:
      name: zeroclaw-env
      namespace: zeroclaw
