apiVersion: v1
kind: Service
metadata:
  name: tts-server
  namespace: tts-server
  labels:
    app: tts-server
spec:
  type: ClusterIP
  selector:
    app: tts-server
  ports:
    - port: 3090
      targetPort: 3090
      protocol: TCP
