---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tts-server-secret
  namespace: tts-server
spec:
  encryptedData:
    auth-token: AgC89dBfI97LIvpmaquzYSLhV+ge1c2nUZ98xpW8Xr+ajdaLz2upcRluQdA86j7+3XHuyyI0iH+VgBmzH9mLBm7MkjGHlCFcbGm6w4gEPxFr0pP2zVXe4q1R8MckqWNGPDDTEwGBsMFWyXwQmOvMz8kUObopCqEj5ERU4E/Yf3Cmwr1vrZI+Ys83/PhVdv6j8sCFPua27xuIA1iaAAvyqVqgt+NNQMvsyDzSMyVZsKttPE8d3NQvS/rDMba37x3fPYEikH1xocObZWfpCH+DNhII/Q0MeEA5Q3S+0TAf0lk/fxXcIhgCPEF6Y6U0Ukf9ng25kUrtVIPOis0nJCEjwS8L8neJEH8EhMQjkZu50CPRVhrqkqAlX4qL9VfvAWmOkp9Tq1tFA8Pzymkpjrc1h3i973OF8Tqoc5okYWw7bir4Yzlw7S2oYxKkjEQmSgGk8Vq8Z9AudWBFp50pqCRfpgUBVHz9r38/mH/NBOLgCQS0St4l4r0I6+VZAy1g+if6v7z6f4SRbDVIQe3PPirMM44fW7i/5fskMQ4X0cXQNj2Mdbzh3VubkQJ8JtGP1H/4jtEfTHk3wPgxPGhynw64ntGeqKHJGJEXE3fgxcrOqkj6hUa9MBnlhBGTJk7mzdfaxcfO6R5SVeuNGcnd1QeRRBtWljbzpXLGdSYerTMSqofgx7r9eTzn2DRQk3XaSJd1Tj8wD4K9E+o83EPxphvWYjMWUtwJ9GOle/8jJtbhZZeoHQ==
    hume-api-key: AgA1L0/da37hT6OKMkif9KHd+Cgemm4fjeSywbumUMJyEGkxKyqlK31Kah0SCpUYTSk9RN42HCijZLpiKEcb80VXsOSupLnwEwFQ626yJL1wcGioIMz56Txc/6sfbMrgVWj21rKUwlDbdg4OdfkOIMosjOiHStaKvaEQVolcYVJGxMmQ+kJiOiB1gYiZU6KQ482qMz9rNnKjX5K2nRjKjkNGyKj/ndvc4YEpcuaKe6VYuCV6EHOKqqG65wZIvka96Ap0JGwaucfjjTsyacWeF22FfrqFfrs0BFgNDi7cS/F83qkx+k9F695+RtJbM5RDXGCQdmJ9V11ZDNXSApUoyKacfUz5vkzJT/tzdQeMhEupu+S2s3B/kFI/pN2+eqdA8bTYpSPdHvvP1Eg3eH8yOvR5+UW9jvP9Iu4qiUcvMOtP0DDg2/DFsSZgz1C1O+imIiPEYWYWHyK4XgrJ1hBbLev9tvy2dH6kxeVVZnAgPw1N1rIb9IUYFxd6FWDXmgma5Ff5KNEPb60NrtW7i6K37Fc20a+Z1RpGfBMXGUQHjF5/Xpir65s+q9gbfT28C3V5teJgW1u/HXB8WhGJRyG7Fv0nyDJvqKntoWKyrhQEuVstXuOchyL3lfxDyt47o0+7bVPfT7FO26/vQQXdWYFQdPnnIOPJOK25PklM+34LetWUJBKi4wKCaqSZViLBu4n+CPGUXn+yEQSh6YJaxflWQDWlR5bsXOBOLO8HJnQ+EgF7lxKqXIp+2fSB0xh/agaf1ZI=
  template:
    metadata:
      name: tts-server-secret
      namespace: tts-server
