apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pawpicks-stock-checker
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    moonrepo.dev/skip-local: "true"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/binary64/moonrepo.git
    path: infra/manifests/pawpicks-stock-checker
    targetRevision: HEAD

  destination:
    server: https://kubernetes.default.svc
    namespace: pawpicks-stock-checker

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
