---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-secret-key
  namespace: authentik
spec:
  encryptedData:
    secret-key: AgBvoFyz3KV/+SdjIa2LdvDHlYJw6r8Ky34g52Zm/UNiQt8HjdVq8GWJC3lIClsar5di8ioDrCk1sB47x7vpFxewFFeqlYvOZl0UYFDzO2RMIlfwxeGPbT8uTcZ5dO7uZzvT/bqeuUftMorAT+w25kEwUHu89XfrWuC7LGEFsyzec+uVTqIHSiOy2cOwvh2Jry7JORdqPLrmKOkPqV6/1l5IVe6EvR5cSVhYPFx4H3jEcvO/SwWyP6NkFPDr8lzP+T71VEXBc7mXkWl6GjkxP8nkNhbrWoAhP5o61Hc2gtxgXlsvb9xnnJUtyAjkU1UZVHJ7TXuGwQj4m2Nu36D+qfrac8/mydQRZT2lOMB3jMmlusz9QtfuADZloLvyL6M2BKlWrivhsFAsrVW1Z69QoF9Y9c7/d8D5TSFWy8mtTRUV7iG/RKxwkzkzGSVUF7l2+bZ+gB6PzJsnWvyZSUgkz75FWRLsq2mBv0yd8FuF6x4gfIXJWcUJpjyr3pdrk4j1dQGcNQHnaDJfjXwIOD7Z8TjU/wJYGCe7Utjh+AKV023zi/AAaxmWHbWI9OVv7jw+zIXnisyVv8arfOXqfIirMwfhhQI0hNwOZVDSmHHpunxAa1Y4B8t8t2QBmkNkyltyJn9LElklkgzDghyBt3DAwr/zVr5UdSkBv2FZJUcaHPOt9pShcM18FmKhEpH1FqH9dQlixDKVSJkd4dsp+biTF08vqQFNnyztqqNKFsk=
  template:
    metadata:
      name: authentik-secret-key
      namespace: authentik
