apiVersion: v1
kind: ConfigMap
metadata:
  name: authentik-branding-blueprint
  namespace: authentik
  labels:
    argocd.argoproj.io/instance: authentik
  annotations:
    moonrepo.dev/skip-local: "true"
    argocd.argoproj.io/sync-wave: "2"
data:
  branding.yaml: |
    # yaml-language-server: $schema=https://goauthentik.io/blueprints/schema.json
    version: 1
    metadata:
      name: Custom Branding
      labels:
        blueprints.goauthentik.io/instantiate: "true"
    entries:
      - model: authentik_brands.brand
        identifiers:
          domain: brandwhisper.cloud
        attrs:
          branding_title: "binary64 central hub"
          branding_logo: "/static/dist/assets/icons/icon_left_brand.svg"
          branding_favicon: "/static/dist/assets/icons/icon.png"
          default: true
