apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-token
  namespace: newrelic
  annotations:
    moonrepo.dev/skip-local: "true"
spec:
  encryptedData:
    apiToken: <PLACEHOLDER_ENCRYPTED_BASE64>
  template:
    type: Opaque
