apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dj-brain
  name: dj-brain
  namespace: radio-dj
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dj-brain
  template:
    metadata:
      labels:
        app: dj-brain
    spec:
      containers:
      - command:
        - /bin/bash
        - /data/radio-dj-script/dj-watcher.sh
        env:
        - name: LITELLM_MASTER_KEY
          valueFrom:
            secretKeyRef:
              key: LITELLM_MASTER_KEY
              name: litellm-gateway-key
        image: ghcr.io/binary64/dj-brain:latest
        imagePullPolicy: Always
        name: dj-brain
        volumeMounts:
        - mountPath: /state
          name: state
        - mountPath: /data/music/dj-override.json
          name: dj-override
        - mountPath: /config/schedule.json
          name: schedule
        - mountPath: /data/radio-dj-script
          name: dj-watcher-script
      imagePullSecrets:
      - name: ghcr-auth
      volumes:
      - emptyDir: {}
        name: state
      - configMap:
          name: dj-override
        name: dj-override
      - configMap:
          name: schedule
        name: schedule
      - configMap:
          name: dj-watcher-script
        name: dj-watcher-script
