apiVersion: v1
kind: Service
metadata:
  name: dj-brain
  namespace: radio-dj
  labels:
    app: dj-brain
spec:
  type: ClusterIP
  selector:
    app: dj-brain
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
