---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hasura-admin-secret
  namespace: radio-dj
spec:
  encryptedData:
    secret: AgAVNqrX7z1t2xuy40BlgGUvs//Re1KZ1lM6h7RSINwFOiyPgJfUoSgC5vANS9K6RkMuQkXnbUW+xxgYzng5xynodSejHO0/jqU2KSxOLlJ2CeMAr+kBvtL/Fq5gjAB8SSTF3MT2i1B6ULC0XtLtj6KcWfK1x+JlFDUyomPgCKwHEZjBVPjBpQrUXB9kO0A91HfeHEgPH7VUL+1kAYACy+8/fgjbs3CCRV9lCwiVyc9GlJfLDMIR7nuyqIZ5Kw1c/1GLB9oM6NP2kVIr8eZADZhUnrnpJFMqsXhk8uaqxYEPvtO1Iq78N/uHpBfluSmMHY1LAm8mgzdMd/6Iu/idqZoP60TfGpCLkJygYnEZ/x5pHjoa7Ue4dlEhhO7x3Fe+U/PT4u3+2t6he3VjwlqWh4KpZuBbbFCKSTIxu7mBCOpIFkB5IvXt+dankb6TS6K3t5vb6cGY9SYyrcra50/2c5mXTVGB7Lx/Y52qq3h0FjhWFQzY+yCszI4KCH1+bDnTntHfM5i9yBfCKEOeW4oJH0YP5gN3K9iBJsSn+UeLyfKhHzXaJrV+hO/+Qh4NC3kQJ/aRfk2RFyBDzl1pD/JfI814fETUDCAKxQf9RPZh0K14712ReqMwE2+ZneFACbXttjiblo0+2y/GpLz3rfl08spdZ+rZQDfc6AcLJMiF4KOGHey/ZjoStLDQELLGnqZduQru3fz78O5eITWRQJ5sOI0JHZtq7j7m7Q0C4adTOwpzPA==
  template:
    metadata:
      name: hasura-admin-secret
      namespace: radio-dj
    type: Opaque
