apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - icecast-secret.yaml
  - icecast-deployment.yaml
  - icecast-service.yaml
  - liquidsoap-secret.yaml
  - liquidsoap-deployment.yaml
  - liquidsoap-service.yaml
  - dj-brain-secret.yaml
  - dj-brain-deployment.yaml
  - dj-brain-service.yaml
