---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: liquidsoap-secret
  namespace: radio-dj
spec:
  encryptedData:
    icecast-source-password: AgC6UFT10tVGbjk0zZCjHmqFH0NO8PrHUr7szTxODGkIH3G7aXNa/k5gCzJYZdWgculB4DpsP+c0UB0anzcq40whcO7tvx71Ac7avDoInX7nlps00j9I/X/EbADIbXEJBL8EOnfOijD8NoG2vAnKUQI0jYcr2kwBkwYuwtjN+TgDa9Dd2GDEKq8m5OxLh5kS/S8oztP23iLhYIQgpMPzdBi3e2zE2tD3SSdxU2Lo1Y4taTrOaG0CeM25QsJRGFmZwXj1eGUXSND9xA5Qu4IaFM4aRteeMRV8PM0VEgaChhQK3PTVnQ7agoU+W2DeAQ6arI68aJg7mk02aawCtXY6ZmcnxtYXYr+IHmKQr8r6zYuYz4BySy15A8U6YZ8N40bg4LqhkSlXxZH3dlZYwsa9jy5r/sZC/DXE3gQ13K8Q3yefGI/xbgtMdy5HOZHZwA6F808OhnZuK5/RzhsR+TEM97TWs2qqAD9lDw/bKa4LWlVnMRpFZC2a2aPeB7RV71pKLnDgXLmMOuTs72TZI108sEwarrmoT+ILT/suT5589sKFDeHSD4tHoEzXc7Dkw5KwfN9ujI5f1kGzk89v2dQA0UI9paq1L9o0Td91jhD/6P1yDAppwrSUVDziluoo75s8LjzlvRLlGQRnt+ueS6jje+PNIswj9g8Hxu3eBXWg+Qhb+4KoySaSuwYMIcV4HH/wbLQ5sUjOG0mVC6g9QAgFwZfOQo09n1a+lEoup7o62OXquA==
    icecast-source-password-url: AgBWWZzTYmAN+Azvf9Op3jLfUHta/Yge5Mxe9Do6hsvZ32XH09lA72KlpuBZS8Rzbb+41JVkSpAi00dKi+OqgRPCZoQvo3dDlFyIr6d/emLOMR5N1j5wLCvi8eG/4JQiaA8G3A8ABBhYDVWGt4XOq0IZ9TPF5owBi3ImtSbna3OZP1MipVCtumUU9d3dINGV36up4kXUT5xbP5Aihhiw+M2i3cSxfUY9JzSLYfv0I5kEZfLugizzRYztCphQtDAqdubKk1gWQ49y5Ez8q/lpCIyvWyS789CUB2eaktgXyaL/LkLpAwx47PltFaOdA8Dh4Csr7lnTCfccXC7DqbtLpxmKn5vwN8x+lLkmpy/LqjQwcHvIhjH9ESmruW5j9OTR+pUiKBUV/EZs93w0SjSzKFx/cigS+EqWRR4RYUt6wEyYuhECX7oJlxTqvpx254saB1lKO3snRQo0S7BU5WUnch1AGNagVTU6Q8QU/4eJnmzPeiMCZfuk7SkIAHAy/G0qSlIsvXkP9oi9N/h1QhyMcT7XYW6SVEofHXNPVa52GTLPs+El0zx2hcfm+evrpX2rJxwH9W70EFwz2tvj657+szkSa2ikWcknPdd4wyQoQdHS1aTiGGmxuWkuObZFb++JOGrrGDT9F52+giZa5TcA+4MBMykIc9gRdwAHciHVMepv/qOTSJWJNzporQGlz9hYmmMyfner9N1nuHiNoBob/Nmky0TE1YDzsagQ/JxeIy0RSJ29P/k=
  template:
    metadata:
      name: liquidsoap-secret
      namespace: radio-dj
    type: Opaque
