---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: liquidsoap-secret
  namespace: radio-dj
spec:
  encryptedData:
    icecast-source-password: AgAwzYS6Hg+sucFjFrHVzmkC2psQYLjxA4wK/mdo3puqzgVsrg+uCvmJk+Giw3laSyAhZBM9aviLxe5rTODX/dX1ZYkdPJSCUflOAcXJBvhfyKzXiw4KbA/f2T90483iH45OsXkcT7+Lqu8PfnZVEhJnu4mcjxCh2hc9Z1+OiUxPybe2rc4Z+kPkvi//MiKXkehlohZLy/ggT0zT5fTeqqGL79+XLqg/2d0REg8CZ58iVXrAiWySkSuqxFNODiA4pzqqFW0samFdHTeoNVd+MQX+p7SFfK5BE4CmRKy/FaJecezqDlraobgDprs7UEs/g9ctkxSTZTzAI+kmG6aCviv4+NUJFrV82E0YgIpaMI4G9n++RVe6nUomA+G9YIAEgLjblOQOM3ZNXIZX61RQ6SHBYD9sD50I4oUJIfMo0ewzIUhTdV3f+qhFpf8Mj8J5CDsuNMWe0a/o2WqWx9F+ru2BKKjd8dO/r2ck16TZOrkw96v/btxk73ru5l8uSG2hE0HetBMscUW9B7blOMmR/3iw3kTVgGbo75HEaZR9r1SJcjX5JTDZjpPr//YYIrxtTBFejp9bBMZVKImjgmaI2YtCx3x1E8Ci+nVZA3BBGPShUjMpq4X6yyZlfdrutsRPvL0lFiEkzb/ZWvChUs7NFgmrhNO7AsCVVmmguDvIKEC+ZrSIZ4dwZB09E2d16NP6Lp7XwtAg6ef5iN4XJTIBY9BlvKlxyM7lMu9SF/N5HFh4oQ==
    icecast-source-password-url: AgBcc2qLSbl9FRJZmzHn3fruUhofc5CWnOkG2E4QO4tLDCQK0VEw25fyFDKYZVy6jtWNWIexov/kz6nYtDFe3yz96taOcmf/3XMLxua6tkc6a1OndRE2OzfMKFYA0Se4pGT9mJ2UO/FJq/WGN65TdES25h9bNnrXb6Omic9tYhSDesNmYKAza/SIpozERSV0RbhQZrW7PKmE70d6Td7blxeOX2pMUrfvnxTUHKTFrcWBGqXEJ0J4spa72faLdMnXVx2vMPRwJtfXqk/BmiCBV7bL9SGClVqt04CGn0bou96tJrrTH/GNV4qDUujsFOPyIYZVHOOZloMIIGfZnEL6QEH/gO17OosyIDB4cj0lLRK5tuhbNqkcOSa0ccSXYd3sVKzLKc1wgkYhw5CjpxZ9Cuc68xqud1fIwcz46rIqN5zvZOw+93dDLfTIf0OGRXr56XCdvrXScGs5/ItzyrOlrIHBS1EJH82Nbm3ENsac9DW4VO9Kx3f34IIavpjhHwpd9zA5fiz2r+OTFDEaVgro59q+L3umhggbKaC2ROP/xL+2yJ7qwuranBOFdqerSYVbky3amzt9qETp3HsIbZnvpsDM1l8a29Qj7VCxueRkdQ4nyjP69IgR6HLB/G/QYK7ewRRGspO/NRF7UHGAC7ps+LmFWV7sePrlQfd1MI7tzso/xFLiQB0r0LcxEw32AFrL1fjySzgqBkec56fWHLm4HcRZrU4JzsKW63KeeThEfrX6EQ==
  template:
    metadata:
      name: liquidsoap-secret
      namespace: radio-dj
    type: Opaque
