apiVersion: v1
kind: Secret
metadata:
  name: litellm-gateway-key
  namespace: radio-dj
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
type: Opaque
data:
  LITELLM_MASTER_KEY: c2stSzB5QzJiNUQ1VzZnZnBWN1NoODBtSnFZM1p4OXdMdDR2Qm4ycg==
