---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: litellm-gateway-key
  namespace: radio-dj
spec:
  encryptedData:
    LITELLM_MASTER_KEY: AgCAfydQfmvI+/+YGnvgV5oKauLvJqL9WW5kW5CveZULOLlXA5Kp7mIRCY4r4fugU/NBbrdki0yROatQ9sjmo1LTuNABl1iDsxg/MwTvbcyWWKfS1gUU5dlI66qgP6PnG7mpDUHmH1U6WG8BpFN0lC15MncUw+dOVYw2eQPnzfdxoPAGU8iPNP9W/YZV5Ai1AFSdg8UEl1xY8ESnEmqKVBZiNtK3ap0CoXiWaVnxsdRyu9tx+C0VfaIAG0CLn0GLUQYcMk9h6m5zo/dDjZG6j0JCohO89XbOYDZnLiVNvEW8BKXKF7KJhr6w7msfZQ7YM98l4amo+0w9fuk/o+VrnKdk1I5tJCoLtqDZGMZLpHZO8cEO1OATg5K+GAzVUveopCuBuqBxxHFuHbN8wvJWfyAKh2fjtW/bEbSa+K4TfTQIt9mPdIzqeYBe3OQgt6E9vPYFrhbvg3yz1wEt4iE5r6oNxibVI5n6S73ol68yhJkur9BfmVbRqqB70TMo0cm7FC9rYwiiiv3y32umIz+3fX7FWOloTJGzftxsSEa3OABXzm4FDDm/yhUhs7fVduFFerTxL/B3GGKj+Eg11a0IYKo+TIdNdgh0n3/VXMJyAnhNLzuQ8repB4Egmsqo0oocfn+4DGUfc2dRYYC0/pflugXK8RvEUfM5/MRTzgmrik1wWy38xm1sXbZDvqJKkJUJjwagb4WifZG45F2kU+ptAC5BLdxDIm4=
  template:
    metadata:
      name: litellm-gateway-key
      namespace: radio-dj
