apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: radio-dj
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/binary64/moonrepo.git
    path: infra/manifests/radio-dj
    targetRevision: HEAD

  destination:
    server: https://kubernetes.default.svc
    namespace: radio-dj

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
