apiVersion: pulumi.com/v1
kind: Stack
metadata:
  name: moonrepo-cloudflare-prod
  namespace: pulumi-operator-system
  annotations:
    # Requires pulumi-operator CRDs and secrets not available in CI
    moonrepo.dev/skip-local: "true"
spec:
  stack: prod
  projectRepo: https://github.com/binary64/moonrepo
  repoDir: infra/pulumi
  branch: refs/heads/master
  destroyOnFinalize: false
  refresh: true
  continueResyncOnCommitMatch: true
  resyncFrequencySeconds: 300
  # Use S3 backend (configured via bootstrap stack)
  backend: s3://moonrepo-pulumi-state-077327148137?region=eu-west-2
  envRefs:
    CLOUDFLARE_API_TOKEN:
      type: Secret
      secret:
        name: cloudflare-api-token-pulumi
        key: token
    # AWS credentials for S3 backend access
    AWS_ACCESS_KEY_ID:
      type: Secret
      secret:
        name: pulumi-aws-credentials
        key: access-key-id
    AWS_SECRET_ACCESS_KEY:
      type: Secret
      secret:
        name: pulumi-aws-credentials
        key: secret-access-key
    AWS_REGION:
      type: Literal
      literal:
        value: eu-west-2
